"""
This type stub file was generated by pyright.
"""

"""
Tools intended to be used inside a Python REPL, like ipython or python itself.
"""
def print_chars(line_length=..., max_char=...): # -> None:
    """Print all chars in the terminal, to help you find that cool one to put in your
    customized spinner or bar. Also useful to determine if your terminal do support them.

    Args:
        line_length (int): the desired characters per line
        max_char (int): the last character in the unicode table to show
            this goes up to 0x10ffff, but after the default value it seems to return
            only question marks, increase it if would like to see more.

    """
    ...

