"""
This type stub file was generated by pyright.
"""

import sys

ENCODING = ...
def buffered_hook_manager(header_template, get_pos, cond_refresh, term): # -> SimpleNamespace:
    """Create and maintain a buffered hook manager, used for instrumenting print
    statements and logging.

    Args:
        header_template (): the template for enriching output
        get_pos (Callable[..., Any]): the container to retrieve the current position
        cond_refresh: Condition object to force a refresh when printing
        term: the current terminal

    Returns:
        a closure with several functions

    """
    ...

def passthrough_hook_manager(): # -> () -> ...:
    ...

def gen_header(header_template, get_pos): # -> () -> Unknown:
    ...

def null_header(): # -> Literal['']:
    ...

if sys.version_info >= (3, 7):
    ...
else:
    ...
