"""
This type stub file was generated by pyright.
"""

def elapsed_text(seconds, precise): # -> str:
    ...

def eta_text(eta): # -> str:
    ...

def simple_eta(logic_total, pos, rate):
    ...

def gen_simple_exponential_smoothing_eta(alfa, logic_total): # -> Generator[Unknown | None, None, None]:
    """Implements a generator with a simple exponential smoothing of the
    eta time series.
    Given alfa and y_hat (t-1), we can calculate the next y_hat:
        y_hat = alfa * y + (1 - alfa) * y_hat
        y_hat = alfa * y + y_hat - alfa * y_hat
        y_hat = y_hat + alfa * (y - y_hat)

    Args:
        alfa (float): the smoothing coefficient
        logic_total (float):

    Returns:

    """
    ...

