"""
This type stub file was generated by pyright.
"""

Show = ...
def showtime(show=..., *, fps=..., length=..., pattern=...): # -> None:
    """Start a show, rendering all styles simultaneously in your screen.

    Args:
        fps (float): the desired frames per second refresh rate
        show (Show): chooses which show will run
        length (int): the bar length, as in configuration options
        pattern (Pattern): to filter objects displayed

    """
    ...

Info = ...
def show_spinners(*, fps=..., length=..., pattern=...): # -> None:
    """Start a spinner show, rendering all styles simultaneously in your screen.

    Args:
        fps (float): the desired frames per second rendition
        length (int): the bar length, as in configuration options
        pattern (Pattern): to filter objects displayed

    """
    ...

def show_bars(*, fps=..., length=..., pattern=...): # -> None:
    """Start a bar show, rendering all styles simultaneously in your screen.

    Args:
        fps (float): the desired frames per second rendition
        length (int): the bar length, as in configuration options
        pattern (Pattern): to filter objects displayed

    """
    ...

def show_themes(*, fps=..., length=..., pattern=...): # -> None:
    """Start a theme show, rendering all styles simultaneously in your screen.

    Args:
        fps (float): the desired frames per second rendition
        length (int): the bar length, as in configuration options
        pattern (Pattern): to filter objects displayed

    """
    ...

_INFO = ...
def exhibit_spinner(spinner): # -> Generator[Unknown, None, None]:
    ...

def exhibit_bar(bar, fps): # -> Generator[tuple[Unknown, float], None, None]:
    ...

